// <auto-generated />
using BookManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagement.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20250222101222_SeedBooks")]
    partial class SeedBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManagement.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookViews")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Shota Rustaveli",
                            BookViews = 500,
                            IsDeleted = false,
                            PublicationYear = 1189,
                            Title = "The Knight in the Panther's Skin"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Chabua Amirejibi",
                            BookViews = 300,
                            IsDeleted = true,
                            PublicationYear = 1975,
                            Title = "Data Tutashkhia"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Vazha-Pshavela",
                            BookViews = 250,
                            IsDeleted = false,
                            PublicationYear = 1890,
                            Title = "The First Step"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Nodar Dumbadze",
                            BookViews = 400,
                            IsDeleted = false,
                            PublicationYear = 1960,
                            Title = "Me, Grandma, Iliko and Ilarioni"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "David Kldiashvili",
                            BookViews = 180,
                            IsDeleted = false,
                            PublicationYear = 1964,
                            Title = "The Father of Soldiers"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Konstantine Gamsakhurdia",
                            BookViews = 350,
                            IsDeleted = true,
                            PublicationYear = 1939,
                            Title = "The Right Hand of the Grand Master"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "David Guramishvili",
                            BookViews = 200,
                            IsDeleted = false,
                            PublicationYear = 1787,
                            Title = "Davitiani"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Alexander Kazbegi",
                            BookViews = 275,
                            IsDeleted = false,
                            PublicationYear = 1881,
                            Title = "Spring in Kartli"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Ilia Chavchavadze",
                            BookViews = 320,
                            IsDeleted = true,
                            PublicationYear = 1890,
                            Title = "The Wine-Cellar"
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "Otar Chiladze",
                            BookViews = 290,
                            IsDeleted = false,
                            PublicationYear = 1962,
                            Title = "The Conductor"
                        },
                        new
                        {
                            Id = 11,
                            AuthorName = "Zviad Kharadze",
                            BookViews = 290,
                            IsDeleted = false,
                            PublicationYear = 1985,
                            Title = "The Dream of the Mountain"
                        },
                        new
                        {
                            Id = 12,
                            AuthorName = "Temur Aghiashvili",
                            BookViews = 350,
                            IsDeleted = true,
                            PublicationYear = 1950,
                            Title = "The Homeland of the Brave"
                        },
                        new
                        {
                            Id = 13,
                            AuthorName = "Otar Chiladze",
                            BookViews = 300,
                            IsDeleted = false,
                            PublicationYear = 1925,
                            Title = "Echoes of the Mountains"
                        },
                        new
                        {
                            Id = 14,
                            AuthorName = "Sandro Shanshiashvili",
                            BookViews = 410,
                            IsDeleted = false,
                            PublicationYear = 1934,
                            Title = "Whispers of the Past"
                        },
                        new
                        {
                            Id = 15,
                            AuthorName = "Akvani Lomaia",
                            BookViews = 370,
                            IsDeleted = true,
                            PublicationYear = 1870,
                            Title = "The Last Song of the Wind"
                        },
                        new
                        {
                            Id = 16,
                            AuthorName = "Levan Lomidze",
                            BookViews = 420,
                            IsDeleted = false,
                            PublicationYear = 1960,
                            Title = "Journey Through the Forgotten Lands"
                        },
                        new
                        {
                            Id = 17,
                            AuthorName = "Giorgi Kharshiladze",
                            BookViews = 260,
                            IsDeleted = false,
                            PublicationYear = 1950,
                            Title = "A Mother's Love"
                        },
                        new
                        {
                            Id = 18,
                            AuthorName = "Giorgi Nikoladze",
                            BookViews = 300,
                            IsDeleted = true,
                            PublicationYear = 1920,
                            Title = "Through the Eyes of the Brave"
                        },
                        new
                        {
                            Id = 19,
                            AuthorName = "Niko Gvetadze",
                            BookViews = 250,
                            IsDeleted = false,
                            PublicationYear = 1945,
                            Title = "The Silent River"
                        },
                        new
                        {
                            Id = 20,
                            AuthorName = "Soslan Geleishvili",
                            BookViews = 330,
                            IsDeleted = true,
                            PublicationYear = 1910,
                            Title = "Winds of Destiny"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
